apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ujyl1rv14-nodejs 
  janus-idp.io/tekton: ujyl1rv14-nodejs
  backstage.io/kubernetes-id: ujyl1rv14-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ujyl1rv14-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml