apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ujyl1rv14-nodejs
  janus-idp.io/tekton: ujyl1rv14-nodejs
  backstage.io/kubernetes-id: ujyl1rv14-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ujyl1rv14-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
