apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ujyl1rv14-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ujyl1rv14-nodejs 
  name: ujyl1rv14-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ujyl1rv14-nodejs 
